run:
  # exit code when at least one issue was found, default is 1
  issues-exit-code: 1

  # include test files or not, default is true
  tests: false

# all available settings of specific linters
linters-settings:
  funlen:
    lines: 120
    statements: 65
  gocyclo:
    min-complexity: 40
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 3
  depguard:
  lll:
    line-length: 150
  nakedret:
    max-func-lines: 0

linters:
  enable:
    - asciicheck
    - copyloopvar
    - dogsled
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - gofumpt
    - goimports
    - gosimple
    - govet
    - lll
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
  disable:
    - gosec
    - nilerr
  presets:
    - bugs
    - unused
  fast: false

